import * as PIXI from "pixi.js";
import { Spriteset_Map, WindowLayer } from "..";

export declare class Scene_Map extends Scene_Message {
  constructor();
  public create(): void;
  public onMapLoaded(): void;
  public onTransfer(): void;
  public start(): void;
  public onTransferEnd(): void;
  public shouldAutosave(): boolean;
  public update(): void;
  public updateMainMultiply(): void;
  public updateMain(): void;
  public isPlayerActive(): boolean;
  public isFastForward(): boolean;
  public stop(): void;
  public terminate(): void;
  public needsFadeIn(): boolean;
  public needsSlowFadeOut(): boolean;
  public updateWaitCount(): boolean;
  public updateDestination(): void;
  public updateMenuButton(): void;
  public hideMenuButton(): void;
  public updateMapNameWindow(): void;
  public isMenuEnabled(): boolean;
  public isMapTouchOk(): boolean;
  public processMapTouch(): void;
  public isAnyButtonPressed(): boolean;
  public onMapTouch(): void;
  public isSceneChangeOk(): boolean;
  public updateScene(): void;
  public createDisplayObjects(): void;
  public createSpriteset(): void;
  public createAllWindows(): void;
  public createMapNameWindow(): void;
  public mapNameWindowRect(): PIXI.Rectangle;
  public createButtons(): void;
  public createMenuButton(): void;
  public updateTransferPlayer(): void;
  public updateEncounter(): void;
  public updateCallMenu(): void;
  public isMenuCalled(): boolean;
  public callMenu(): void;
  public updateCallDebug(): void;
  public isDebugCalled(): boolean;
  public fadeInForTransfer(): void;
  public fadeOutForTransfer(): void;
  public launchBattle(): void;
  public stopAudioOnBattleStart(): void;
  public startEncounterEffect(): void;
  public updateEncounterEffect(): void;
  public snapForBattleBackground(): void;
  public startFlashForEncounter(duration: unknown): void;
  public encounterEffectSpeed(): number;

  public _encounterEffectDuration: number;
  public _lastMapWasNull: boolean;
  public _mapLoaded: boolean;
  public visible: boolean;
  public _menuEnabled: boolean;
  public _touchCount: number;
  public _transfer: boolean;
  public _waitCount: number;
  public menuCalling: boolean;
  public _spriteset: Spriteset_Map;
  public _windowLayer: WindowLayer;
}
