import { AudioObject, ColorTone } from "../other";

export declare class Game_System {
  constructor();
  public isJapanese(): boolean;
  public isChinese(): boolean;
  public isKorean(): boolean;
  public isCJK(): boolean;
  public isRussian(): boolean;
  public isSideView(): boolean;
  public isAutosaveEnabled(): boolean;
  public isSaveEnabled(): boolean;
  public disableSave(): void;
  public enableSave(): void;
  public isMenuEnabled(): void;
  public disableMenu(): void;
  public enableMenu(): void;
  public isEncounterEnabled(): boolean;
  public disableEncounter(): void;
  public enableEncounter(): void;
  public isFormationEnabled(): boolean;
  public disableFormation(): void;
  public enableFormation(): void;
  public battleCount(): number;
  public winCount(): number;
  public escapeCount(): number;
  public saveCount(): number;
  public versionId(): number;
  public savefileId(): number;
  public setSavefileId(savefileId: number): void;
  public windowTone(): ColorTone;
  public setWindowTone(value: ColorTone): void;
  public battleBgm(): AudioObject;
  public setBattleBgm(value: AudioObject): void;
  public victoryMe(): AudioObject;
  public setVictoryMe(value: AudioObject): void;
  public defeatMe(): AudioObject;
  public setDefeatMe(value: AudioObject): void;
  public onBattleStart(): void;
  public onBattleWin(): void;
  public onBattleEscape(): void;
  public onBeforeSave(): void;
  public onAfterLoad(): void;
  public playtime(): number;
  public playtimeText(): string;
  public saveBgm(): void;
  public replayBgm(): void;
  public saveWalkingBgm(): void;
  public replayWalkingBgm(): void;
  public saveWalkingBgm2(): void;
  public mainFontFace(): string;
  public numberFontFace(): string;
  public mainFontSize(): number;
  public windowPadding(): number;
  public windowOpacity(): number;

  public _battleBgm: AudioObject;
  public _battleCount: number;
  public _bgmOnSave: AudioObject;
  public _bgsOnSave: AudioObject;
  public _defeatMe: AudioObject;
  public _encounterEnabled: boolean;
  public _escapeCount: number;
  public _formationEnabled: boolean;
  public _framesOnSave: number;
  public _menuEnabled: boolean;
  public _saveCount: number;
  public _saveEnabled: boolean;
  public _savedBgm: AudioObject;
  public _savefileId: number;
  public _versionId: number;
  public _victoryMe: AudioObject;
  public _walkingBgm: AudioObject;
  public _winCount: number;
  public _windowTone: ColorTone;
}
