export declare class Game_CharacterBase {
  constructor();
  public initMembers(): void;
  public pos(x: number, y: number): boolean;
  public posNt(x: number, y: number): boolean;
  public moveSpeed(): number;
  public setMoveSpeed(moveSpeed: number): void;
  public moveFrequency(): number;
  public setMoveFrequency(moveFrequency: number): void;
  public opacity(): number;
  public setOpacity(opacity: number): void;
  public blendMode(): number;
  public setBlendMode(blendMode: number): void;
  public isNormalPriority(): number;
  public setPriorityType(priorityType: number): void;
  public isMoving(): boolean;
  public isJumping(): boolean;
  public jumpHeight(): number;
  public isStopping(): boolean;
  public checkStop(threshold: number): boolean;
  public resetStopCount(): void;
  public realMoveSpeed(): number;
  public distancePerFrame(): number;
  public isDashing(): boolean;
  public isDebugThrough(): boolean;
  public straighten(): void;
  public reverseDir(d: number): number;
  public canPass(x: number, y: number, d: number): boolean;
  public canPassDiagonally(
    x: number,
    y: number,
    horz: number,
    vert: number
  ): boolean;
  public isMapPassable(x: number, y: number, d: number): boolean;
  public isCollidedWithCharacters(x: number, y: number): boolean;
  public isCollidedWithEvents(x: number, y: number): boolean;
  public isCollidedWithVehicles(x: number, y: number): boolean;
  public setPosition(x: number, y: number): void;
  public copyPosition(character: Game_CharacterBase): void;
  public locate(x: number, y: number): void;
  public direction(): number;
  public setDirection(d: number): void;
  public isTile(): boolean;
  public isObjectCharacter(): boolean;
  public shiftY(): number;
  public scrolledX(): number;
  public scrolledY(): number;
  public screenX(): number;
  public screenY(): number;
  public screenZ(): number;
  public isNearTheScreen(): boolean;
  public update(): void;
  public updateStop(): void;
  public updateJump(): void;
  public updateMove(): void;
  public updateAnimation(): void;
  public animationWait(): number;
  public updateAnimationCount(): void;
  public updatePattern(): void;
  public maxPattern(): number;
  public pattern(): number;
  public setPattern(pattern: number): void;
  public isOriginalPattern(): boolean;
  public resetPattern(): void;
  public refreshBushDepth(): void;
  public isOnLadder(): boolean;
  public isOnBush(): boolean;
  public terrainTag(): number;
  public regionId(): number;
  public increaseSteps(): void;
  public tileId(): number;
  public characterName(): string;
  public characterIndex(): number;
  public setImage(characterName: string, characterIndex: number): void;
  public setTileImage(tileId: number): void;
  public checkEventTriggerTouchFront(d: number): void;
  public checkEventTriggerTouch(): boolean;
  public isMovementSucceeded(): boolean;
  public setMovementSuccess(success: boolean): void;
  public moveStraight(d: number): void;
  public moveDiagonally(horz: number, vert: number): void;
  public jump(xPlus: number, yPlus: number): void;
  public hasWalkAnime(): boolean;
  public setWalkAnime(walkAnime: boolean): void;
  public hasStepAnime(): boolean;
  public setStepAnime(stepAnime: boolean): void;
  public isDirectionFixed(): boolean;
  public setDirectionFix(directionFix: boolean): void;
  public isThrough(): boolean;
  public setThrough(through: boolean): void;
  public isTransparent(): boolean;
  public bushDepth(): number;
  public setTransparent(transparent: boolean): void;
  public startAnimation(): void;
  public startBalloon(): void;
  public isAnimationPlaying(): boolean;
  public isBalloonPlaying(): boolean;
  public endAnimation(): void;
  public endBalloon(): void;

  public _animationCount: number;
  public _animationId: number;
  public _animationPlaying: boolean;
  public _balloonId: number;
  public _balloonPlaying: boolean;
  public _blendMode: number;
  public _bushDepth: number;
  public _characterIndex: string;
  public _characterName: string;
  public _direction: number;
  public _directionFix: boolean;
  public _isObjectCharacter: boolean;
  public _jumpCount: number;
  public _jumpPeak: number;
  public _moveFrequency: number;
  public _moveSpeed: number;
  public _movementSuccess: boolean;
  public _opacity: number;
  public _pattern: number;
  public _priorityType: number;
  public _realX: number;
  public _realY: number;
  public _stepAnime: boolean;
  public _stopCount: number;
  public _through: boolean;
  public _tileId: number;
  public _transparent: boolean;
  public _walkAnime: boolean;
  public _x: number;
  public _y: number;
}
