import { Game_CharacterBase } from "..";
import { Map_EventPageMoveRoute } from "../data";

export declare class Game_Character extends Game_CharacterBase {
  constructor();
  public initMembers(): void;
  public memorizeMoveRoute(): void;
  public restoreMoveRoute(): void;
  public isMoveRouteForcing(): boolean;
  public setMoveRoute(moveRoute: Map_EventPageMoveRoute): void;
  public forceMoveRoute(moveRoute: Map_EventPageMoveRoute): void;
  public updateStop(): void;
  public updateRoutineMove(): void;
  public processMoveCommand(command: Map_EventPageMoveRoute["list"][0]): void;
  public deltaXFrom(x: number): number;
  public deltaYFrom(y: number): number;
  public moveRandom(): void;
  public moveTowardCharacter(character: Game_CharacterBase): void;
  public moveAwayFromCharacter(character: Game_CharacterBase): void;
  public turnTowardCharacter(character: Game_CharacterBase): void;
  public turnAwayFromCharacter(character: Game_CharacterBase): void;
  public turnTowardPlayer(): void;
  public turnAwayFromPlayer(): void;
  public moveTowardPlayer(): void;
  public moveAwayFromPlayer(): void;
  public moveForward(): void;
  public moveBackward(): void;
  public processRouteEnd(): void;
  public advanceMoveRouteIndex(): void;
  public turnRight90(): void;
  public turnLeft90(): void;
  public turn180(): void;
  public turnRightOrLeft90(): void;
  public turnRandom(): void;
  public swap(character: Game_CharacterBase): void;
  public findDirectionTo(goalX: number, goalY: number): number;
  public searchLimit(): number;

  static ROUTE_CHANGE_BLEND_MODE: 43;
  static ROUTE_CHANGE_FREQ: 30;
  static ROUTE_CHANGE_IMAGE: 41;
  static ROUTE_CHANGE_OPACITY: 42;
  static ROUTE_CHANGE_SPEED: 29;
  static ROUTE_DIR_FIX_OFF: 36;
  static ROUTE_DIR_FIX_ON: 35;
  static ROUTE_END: 0;
  static ROUTE_JUMP: 14;
  static ROUTE_MOVE_AWAY: 11;
  static ROUTE_MOVE_BACKWARD: 13;
  static ROUTE_MOVE_DOWN: 1;
  static ROUTE_MOVE_FORWARD: 12;
  static ROUTE_MOVE_LEFT: 2;
  static ROUTE_MOVE_LOWER_L: 5;
  static ROUTE_MOVE_LOWER_R: 6;
  static ROUTE_MOVE_RANDOM: 9;
  static ROUTE_MOVE_RIGHT: 3;
  static ROUTE_MOVE_TOWARD: 10;
  static ROUTE_MOVE_UP: 4;
  static ROUTE_MOVE_UPPER_L: 7;
  static ROUTE_MOVE_UPPER_R: 8;
  static ROUTE_PLAY_SE: 44;
  static ROUTE_SCRIPT: 45;
  static ROUTE_STEP_ANIME_OFF: 34;
  static ROUTE_STEP_ANIME_ON: 33;
  static ROUTE_SWITCH_OFF: 28;
  static ROUTE_SWITCH_ON: 27;
  static ROUTE_THROUGH_OFF: 38;
  static ROUTE_THROUGH_ON: 37;
  static ROUTE_TRANSPARENT_OFF: 40;
  static ROUTE_TRANSPARENT_ON: 39;
  static ROUTE_TURN_180D: 22;
  static ROUTE_TURN_90D_L: 21;
  static ROUTE_TURN_90D_R: 20;
  static ROUTE_TURN_90D_R_L: 23;
  static ROUTE_TURN_AWAY: 26;
  static ROUTE_TURN_DOWN: 16;
  static ROUTE_TURN_LEFT: 17;
  static ROUTE_TURN_RANDOM: 24;
  static ROUTE_TURN_RIGHT: 18;
  static ROUTE_TURN_TOWARD: 25;
  static ROUTE_TURN_UP: 19;
  static ROUTE_WAIT: 15;
  static ROUTE_WALK_ANIME_OFF: 32;
  static ROUTE_WALK_ANIME_ON: 31;
  public _moveRoute: Map_EventPageMoveRoute;
  public _moveRouteForcing: boolean;
  public _moveRouteIndex: number;
  public _originalMoveRoute: Map_EventPageMoveRoute;
  public _originalMoveRouteIndex: number;
  public _waitCount: number;
}
